// Generated by CoffeeScript 1.8.0
(function() {
  var Client, api, async, config, logger, util, _;

  _ = require('lodash');

  async = require('async');

  logger = require('graceful-logger');

  api = require('./api');

  util = require('./util');

  config = require('./config');

  Client = (function() {
    function Client(token) {
      this.token = token != null ? token : null;
    }

    Client.prototype.auth = function(token) {
      this.token = token;
      return this;
    };

    Client.prototype.call = function(apiKey, params, callback) {
      if (callback == null) {
        callback = function() {};
      }
      return api.list((function(_this) {
        return function(err, apiMap) {
          var method, path, url, _ref;
          if (typeof params === 'function') {
            callback = params;
            params = {};
          }
          if (apiMap[apiKey] == null) {
            return callback(err || new Error('NO_SUCH_API'));
          }
          _ref = apiMap[apiKey], path = _ref.path, method = _ref.method;
          url = config.apiHost + path.split('/').map(function(k) {
            var _k;
            if (k[0] !== ':') {
              return k;
            }
            k = k.slice(1);
            _k = params[k];
            delete params[k];
            return _k;
          }).join('/');
          if (_this.token) {
            params.token = _this.token;
          }
          params.appToken = config.appToken;
          logger.info("send request: " + url);
          return util.request(url, method, params, callback);
        };
      })(this));
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
