// Generated by CoffeeScript 1.7.1
(function() {
  var Client, apis, async, config, util, _;

  _ = require('lodash');

  async = require('async');

  apis = require('./apis');

  util = require('./util');

  config = require('./config');

  Client = (function() {
    function Client(token) {
      this.token = token != null ? token : null;
    }

    Client.prototype.auth = function(token) {
      this.token = token;
      return this;
    };

    Client.prototype.discover = function(callback) {
      var discoverUrl;
      if (callback == null) {
        callback = function() {};
      }
      discoverUrl = config.apiHost + '/v1/discover';
      util.request(discoverUrl, 'get', function(err, data) {
        if (err == null) {
          apis = _.extend(apis, data);
        }
        return callback(err, data);
      });
      return this;
    };

    Client.prototype.call = function(api, params, callback) {
      var method, path, url, _ref;
      if (callback == null) {
        callback = function() {};
      }
      if (_.isEmpty(apis)) {
        return async.waterfall([
          (function(_this) {
            return function(next) {
              return _this.discover(next);
            };
          })(this), (function(_this) {
            return function(apis, next) {
              return _this.call(api, params, next);
            };
          })(this)
        ], callback);
      }
      if (apis[api] == null) {
        return callback(new Error('NO_SUCH_API'));
      }
      _ref = apis[api], path = _ref.path, method = _ref.method;
      url = config.apiHost + path.replace(/\:(.*)?\/?/i, function(m1, m2) {
        var _m2;
        _m2 = params[m2];
        delete params[m2];
        return _m2;
      });
      if (this.token) {
        params.token = this.token;
      }
      params.clientId = config.clientId;
      params.clientSecret = config.clientSecret;
      return util.request(url, method, params, callback);
    };

    return Client;

  })();

  module.exports = Client;

}).call(this);
