// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    clientId: 'your client id',
    clientSecret: 'your client secret',
    apiHost: 'https://talk.ai',
    version: 1
  };

}).call(this);
