// Generated by CoffeeScript 1.7.1
(function() {
  var Robot, http;

  http = require('http');

  Robot = (function() {
    function Robot() {}

    Robot.prototype.online = function() {};

    Robot.prototype.offline = function() {};

    return Robot;

  })();

  module.exports = new Robot;

}).call(this);
