// Generated by CoffeeScript 1.7.1
(function() {
  var json, server;

  json = require('body-parser').json();

  server = module.exports;

  server.response = function(req, res) {
    var event, talk;
    event = (req.body || {}).event;
    res.end('PONG');
    if (!event) {
      return;
    }
    talk = require('./talk');
    talk.emit(event, req.body);
    return talk.emit('*', req.body);
  };

  server.initialHandler = function(app, options) {
    var prefix;
    if (options == null) {
      options = {};
    }
    server.app = app;
    prefix = options.prefix;
    prefix || (prefix = '/');
    app.post(prefix, function(req, res) {
      if (req.body) {
        return server.response(req, res);
      } else {
        return json(req, res, function() {
          return server.response(req, res);
        });
      }
    });
    return server;
  };

}).call(this);
