// Generated by CoffeeScript 1.8.0
(function() {
  var Service, express, json, logger,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  express = require('express');

  json = require('body-parser').json;

  logger = require('graceful-logger').format('medium');

  Service = (function() {
    function Service(talk, app, options) {
      var prefix;
      this.talk = talk;
      this.app = app;
      if (options == null) {
        options = {};
      }
      this.emit = __bind(this.emit, this);
      this.app || (this.app = express());
      prefix = options.prefix;
      prefix || (prefix = '/');
      this.app.use(json());
      this.app.post(prefix, this.emit);
    }

    Service.prototype.emit = function(req, res, next) {
      var data, event, _ref;
      _ref = req.body || {}, event = _ref.event, data = _ref.data;
      res.end('PONG');
      if (!event) {
        return;
      }
      this.talk.emit(event, data);
      return this.talk.emit('*', data);
    };

    Service.prototype.listen = function(port, callback) {
      if (callback == null) {
        callback = function() {};
      }
      this.app.listen(port, callback);
      return this;
    };

    return Service;

  })();

  module.exports = Service;

}).call(this);
