// Generated by CoffeeScript 1.7.1
(function() {
  var Talk, config, talk, _;

  _ = require('lodash');

  config = require('./config');

  Talk = (function() {
    function Talk(options) {
      if (options == null) {
        options = {};
      }
      this.options = options;
    }

    Talk.prototype.auth = function(accessKey, secretKey) {
      this.options.accessKey = accessKey;
      this.options.secretKey = secretKey;
      return this;
    };

    Talk.prototype.landingUrl = function(token, room) {};

    return Talk;

  })();

  talk = new Talk;

  talk.Talk = Talk;

  module.exports = talk;

}).call(this);
