// Generated by CoffeeScript 1.8.0
(function() {
  var request;

  request = require('request');

  exports.request = function(url, method, params, callback) {
    var options;
    if (params == null) {
      params = {};
    }
    if (callback == null) {
      callback = function() {};
    }
    if (toString.call(params) === '[object Function]') {
      callback = params;
      params = {};
    }
    options = {
      method: (typeof method.toUpperCase === "function" ? method.toUpperCase() : void 0) || 'GET',
      url: url
    };
    options.headers = {
      "Content-Type": "application/json"
    };
    if (options.method === 'GET') {
      options.qs = params;
    } else {
      options.body = JSON.stringify(params);
    }
    options.timeout = 10000;
    return request(options, function(err, res, body) {
      var e;
      try {
        body = JSON.parse(body);
      } catch (_error) {
        e = _error;
        body = {};
      }
      if ((err != null) || (res != null ? res.statusCode : void 0) !== 200) {
        err || (err = new Error(body.message));
        err.code || (err.code = body.code);
        return callback(err);
      } else {
        return callback(null, body);
      }
    });
  };

}).call(this);
