// Generated by CoffeeScript 1.7.1
(function() {
  var request, util, _;

  request = require('request');

  _ = require('lodash');

  util = {
    request: function(options, callback) {
      if (options == null) {
        options = {};
      }
      if (callback == null) {
        callback = function() {};
      }
      return request(options, function(err, res, result) {
        var e;
        if ((err != null) || (result == null)) {
          return callback(err);
        }
        try {
          result = JSON.parse(result);
        } catch (_error) {
          e = _error;
          result = {};
        }
        return callback(err, result);
      });
    }
  };

  module.exports = util;

}).call(this);
